/**
 * Database row + logical-schema types for the shared-JSONB tenant model
 * (Story 1.2). Shared by the guarded write layer (`mutate.ts`), the read
 * layer (`records.ts`), the seed script, and the RLS isolation test.
 *
 * There is NO per-tenant physical table: a "table" is logical — a `table_key`
 * plus a `TableDefinition` in the org's `org_schemas.definition`.
 */

/** A single field within a logical table definition. */
export type FieldDefinition = {
  /** Normalized snake_case key used inside `records.data`. */
  key: string;
  /** Human-facing column label (rename edits this, not `key`). */
  label: string;
  /**
   * Rendering/validation hint. Story 1.4 widened the union to the full
   * generation contract: the base scalar set plus `datetime`, `email`, `phone`.
   * Story 1.8 adds `relation` — a single-reference link to another table's
   * record (see `relationConfig`). A `relation` cell stores the target record's
   * UUID in `records.data`, never the label; the label resolves at read time
   * from the target table's `displayField`.
   */
  type:
    | "text"
    | "number"
    | "date"
    | "datetime"
    | "boolean"
    | "currency"
    | "email"
    | "phone"
    | "relation";
  /**
   * Present only when `type === "relation"` (Story 1.8). Describes the link:
   * `targetTable` is the `TableDefinition.key` this field points at, and
   * `cardinality` is `"one"` at MVP (a single reference). `"many"` (multi-select)
   * is Growth-only and rejected by the validator on the generation path.
   */
  relationConfig?: {
    targetTable: string;
    cardinality: "one" | "many";
  };
  /** Plain-language reason this field exists (FR46 explainability). */
  reason?: string;
  /** Append-only hide flag — a display concern, never a data delete. */
  hidden?: boolean;
  /** Marks PII for PIPEDA handling (FR40). */
  sensitive?: boolean;
};

/** A logical table: a normalized key + its ordered field definitions. */
export type TableDefinition = {
  /** Normalized snake_case logical-table key (matches `records.table_key`). */
  key: string;
  /** Human-facing table label. */
  label: string;
  /** Plain-language reason this table exists (FR46 explainability). */
  reason?: string;
  /**
   * Append-only hide flag — a display concern, never a data delete. Mirrors
   * `FieldDefinition.hidden`: a removed table drops out of `visibleTables`
   * (and the tablist) while its definition and any `records` stay intact.
   * Backward-compatible optional JSONB field — no migration.
   */
  hidden?: boolean;
  /**
   * The canonical label field for this table (Story 1.8, FR75): the non-hidden
   * field key whose value represents a row wherever it appears as a relation
   * reference. Provisioning defaults it (first non-hidden `text` field, else the
   * first non-hidden field) when generation omits it. Optional JSONB field,
   * backward-compatible — no migration.
   */
  displayField?: string;
  /** Ordered field definitions rendered as columns. */
  fields: FieldDefinition[];
};

/** The full authoritative logical schema stored in `org_schemas.definition`. */
export type SchemaDefinition = {
  tables: TableDefinition[];
  /**
   * True when this schema was provisioned from the hardcoded universal fallback
   * template (Story 1.5), not generated by the LLM. Persisted into
   * `org_schemas.definition` (no migration) so it survives read-back and claim,
   * and mirrored into the generate response so `/generate` can show the subtle
   * "starter template" banner. Successful generations omit it (falsy).
   */
  isFallback?: boolean;
};

// --- Row types (mirror the platform migration) -----------------------------

export type OrganizationRow = {
  id: string;
  name: string;
  slug: string;
  created_at: string;
  updated_at: string;
};

export type PrincipalType = "human" | "agent";
export type MemberRole = "admin" | "member";

export type OrgMemberRow = {
  id: string;
  organization_id: string;
  user_id: string;
  principal_type: PrincipalType;
  role: MemberRole;
  created_at: string;
};

export type RecordRow = {
  id: string;
  organization_id: string;
  table_key: string;
  data: Record<string, unknown>;
  actor_id: string | null;
  idempotency_key: string | null;
  version: number;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
};

export type OrgSchemaRow = {
  organization_id: string;
  definition: SchemaDefinition;
  created_at: string;
  updated_at: string;
};

/**
 * Durable finalize record for a magic-link claim (Story 2.1). Written pre-auth
 * by the claim POST (service-role) and resolved by `token` on the auth
 * callback. `consumed_at` guards idempotency: a second finalize with the same
 * token is a no-op. Mirrors `20260924060000_pending_claims.sql`.
 */
export type PendingClaimRow = {
  id: string;
  token: string;
  email: string;
  session_org_id: string;
  consent_accepted_at: string;
  policy_version: string;
  slug_base: string;
  created_at: string;
  expires_at: string;
  consumed_at: string | null;
};

/** The non-deleted-row `data` returned by the read layer, plus its identity. */
export type RecordData = {
  id: string;
  version: number;
  data: Record<string, unknown>;
};

/** Business entity type (text + CHECK in the DB, never a Postgres enum). */
export type BusinessEntityType =
  | "sole_proprietor"
  | "partnership"
  | "corporation"
  | "nonprofit"
  | "other";

/** Default invoice language (text + CHECK in the DB). */
export type BusinessProfileLanguage = "en" | "fr";

/**
 * Singleton-per-org Business Profile row (Story 12.1) — the typed platform table
 * that captures the owner's legal identity, tax registration, addresses, default
 * terms/language, and a structured payment-instructions block once. Keyed by
 * `organization_id` (one row per org). Mirrors every column of
 * `20260928120000_business_profiles.sql`. NOT the JSONB records store.
 */
export type BusinessProfileRow = {
  organization_id: string;
  legal_name: string;
  operating_name: string | null;
  entity_type: BusinessEntityType | null;
  jurisdiction: string | null;
  gst_hst_number: string | null;
  gst_hst_effective_date: string | null;
  logo_path: string | null;
  business_address: string | null;
  mailing_address: string | null;
  default_payment_terms: string | null;
  default_language: BusinessProfileLanguage;
  payment_etransfer_email: string | null;
  payment_cheque_payable_to: string | null;
  payment_cheque_address: string | null;
  payment_card_link: string | null;
  actor_id: string | null;
  created_at: string;
  updated_at: string;
};

/**
 * Full invoice lifecycle status (text + CHECK in the DB, never a Postgres enum).
 * The whole vocabulary is defined now (Story 12.2 migration) so 12.3-12.8 need no
 * ALTER; Story 12.2 only ever writes `'draft'`. Transitions are owned by 12.4+.
 */
export type InvoiceStatus = "draft" | "issued" | "paid" | "overdue" | "void";

/** The invoice language (text + CHECK in the DB). */
export type InvoiceLanguage = "en" | "fr";

/**
 * Frozen supplier identity + payment instructions snapshot (Story 12.4, I6). Captured
 * from the Business Profile INSIDE the issue transaction; after issue all rendering
 * reads from here, never the live `business_profiles` row. `null` before issue.
 */
export type SupplierSnapshot = {
  legal_name: string;
  operating_name: string | null;
  entity_type: BusinessEntityType | null;
  jurisdiction: string | null;
  gst_hst_number: string | null;
  gst_hst_effective_date: string | null;
  logo_path: string | null;
  business_address: string | null;
  mailing_address: string | null;
  default_payment_terms: string | null;
  payment_etransfer_email: string | null;
  payment_cheque_payable_to: string | null;
  payment_cheque_address: string | null;
  payment_card_link: string | null;
  language: BusinessProfileLanguage;
};

/**
 * Frozen linked-customer snapshot (Story 12.4, I6). Captures the linked record's
 * identity at issue; `null` for a standalone invoice (no `customer_record_id`). After
 * issue `customer_record_id` is a back-reference only — rendering reads from here.
 */
export type CustomerSnapshot = {
  record_id: string;
  table_key: string;
  display_label: string | null;
  data: Record<string, unknown>;
};

/**
 * Typed platform invoice parent row (Story 12.2) — NOT the JSONB records store.
 * Mirrors every column of `20260928120200_invoices.sql` (money columns from 12.3;
 * issue columns from 12.4). Drafting starts at `status='draft'`; 12.4 flips it to
 * `'issued'` and freezes `invoice_number` / `issue_date` / the snapshots /
 * `share_token`. `pdf_path` is added by 12.5. `customer_record_id` is a LOOSE
 * reference to `records.id` (ON DELETE SET NULL); the customer label resolves at read
 * time for a draft and from `customer_snapshot` after issue.
 */
export type InvoiceRow = {
  id: string;
  organization_id: string;
  customer_record_id: string | null;
  place_of_supply_province: string | null;
  language: InvoiceLanguage;
  status: InvoiceStatus;
  version: number;
  actor_id: string | null;
  /**
   * Money totals (Story 12.3). Written ONLY from `computeInvoiceTotals` output on
   * every draft save (Invariant I2): `subtotal = Σ line amounts`, `tax_total =
   * Σ tax lines` (0 when no tax applies), `total = subtotal + tax_total`. Existing
   * 12.2 drafts read as 0 until their next save. PostgREST returns numeric columns
   * as strings, so they are typed `number | string` at the row boundary.
   */
  subtotal: number | string;
  tax_total: number | string;
  total: number | string;
  /**
   * Issue-time frozen columns (Story 12.4). All null until issued. `invoice_number`
   * is the gap-free per-org integer (I1; PostgREST returns bigint as a string);
   * `issue_date` is the server-authoritative `YYYY-MM-DD`; the snapshots freeze
   * supplier/customer identity (I6); `share_token` is the one-time 128-bit token (I4).
   */
  invoice_number: number | string | null;
  issue_date: string | null;
  supplier_snapshot: SupplierSnapshot | null;
  customer_snapshot: CustomerSnapshot | null;
  share_token: string | null;
  created_at: string;
  updated_at: string;
};

/**
 * Typed invoice line-item row (Story 12.2) — a child of `invoices`. Mirrors every
 * column of `20260928120300_invoice_line_items.sql`. `organization_id` is
 * denormalized from the parent for RLS. `amount = round(quantity * unit_price, 2)`
 * is computed server-side by the single canonical `computeLineAmount` (I2) and
 * stored — never recomputed in SQL. Numeric columns come back as strings from
 * PostgREST, so they are typed `number | string` at the row boundary.
 */
export type InvoiceLineItemRow = {
  id: string;
  invoice_id: string;
  organization_id: string;
  description: string;
  quantity: number | string;
  unit_price: number | string;
  amount: number | string;
  sort_order: number;
  created_at: string;
  updated_at: string;
};

/**
 * Typed invoice tax-line row (Story 12.3) — a child of `invoices`. Mirrors every
 * column of `20260928120500_invoice_totals_and_tax_lines.sql`. `organization_id` is
 * denormalized from the parent for RLS. For the MVP Ontario path there is exactly
 * ONE HST row per invoice when tax applies; `tax_amount = round(base × rate, 2)` is
 * computed once on the subtotal by the canonical `computeInvoiceTotals` (I3) and
 * stored — never recomputed in SQL. `label` is the canonical stored name (`HST`);
 * the form/PDF translate it for display. Numeric columns come back as strings from
 * PostgREST, so they are typed `number | string` at the row boundary.
 */
export type InvoiceTaxLineRow = {
  id: string;
  invoice_id: string;
  organization_id: string;
  label: string;
  rate: number | string;
  base: number | string;
  tax_amount: number | string;
  sort_order: number;
  created_at: string;
  updated_at: string;
};
